custom:
  settings: ${file(src/settings.js)}
  client:
    bucketName: ${self:custom.settings.staticAssetsS3Bucket}
    distributionFolder: app_dist
    indexDocument: root.html

service:
  name: ${self:custom.settings.serviceName}

plugins:
  - serverless-finch

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.settings.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:GetObject
      Resource:
        Fn::GetAtt:
          - StaticAssetsBucket
          - Arn

resources:
  Resources:
    StaticAssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.settings.staticAssetsS3Bucket}

package:
  exclude:
    - '**'
  include:
    - src/serverless_handlers.js
    - serverless_dist/ssr_handler.js

functions:
  ssr:
    handler: src/serverless_handlers.ssr
    events:
      - http:
          method: get
          path: ssr

