[package]
name = "interactive-binary-decoder-rs"
version = "0.1.0"
authors = ["W. Brian Gourlie <bgourlie@gmail.com>"]

[dependencies]
stdweb = { git = "https://github.com/koute/stdweb", features = ["nightly"]}
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
